### ISSUE TITLE
Email address is wired and UserModel email validation fail for LDAP provider

### ISSUE THREAD

**Issue by mike-aungsan** [strongloop/loopback-component-passport#119] opened 2016-01-16 01:22 UTC
For LDAP provider, user email become username@domain.com@loopback.provider.com  and validation fail.

loopback-component-passport:
All third party accounts will login with an email of uniqueID@loopback.provider.com example 123456@loopback.facebook.com

Line 702:
    // email validation regex
    var re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
   
    //UserModel.validatesFormatOf('email', {with: re, message: 'Must provide a valid email'});

https://github.com/strongloop/loopback/issues/1963

**Comment by loay** [comment] 2016-01-26 18:33
Duplicate of [strongloop/loopback#1963]

**Closed by loay** 2016-01-26 18:33 UTC
Labels: duplicate, triage
