### ISSUE TITLE
No way to catch errors from a local login

### ISSUE THREAD

**Issue by gausie** [strongloop/loopback-component-passport#99] opened 2015-11-02 14:14 UTC
Using passport-local, errors from User.login are passed down the chain of express middleware, instead of being used in a failureRedirect.

I want to do something with failed logins (i.e. make a more descriptive error name) but cannot.

**Comment by loay** [comment] 2015-11-17 16:29
Hi @gausie 
Thanks for reporting this issue. I am not sure if I follow your request concerning the local login. 
If you look in passport-configurator.js, you will see this part: 
```
return done(null, false, {message: 'Incorrect password.'});
```
or 
```
return done(null, false, {message: 'Incorrect username.'});
```

If that's not what you are looking for, please provide more information about the issue or refer to a repo I can use to reproduce the issue. Thanks.

**Comment by loay** [comment] 2015-12-01 00:08
@gausie did you have the chance to test that?
Thanks

**Comment by vshushkov** [comment] 2015-12-19 16:42
Hi, @gausie @loay
I've made a related commit https://github.com/strongloop/loopback-component-passport/pull/112

**Comment by hackerunet** [comment] 2016-07-19 15:06
Dear developers, I've been looking a lot on this error, the problem root is basically or could be basically lack of UP TO DATE documentation.
In my case I'm receiving 
TypeError: req.flash is not a function
So, why is that been triggered? In the official stronloop documentation a reference to a passport template is always suggested:
`https://docs.strongloop.com/display/public/LB/Configuring+providers.json
```
https://docs.strongloop.com/display/public/LB/Configuring+providers.json
```
So again the OUT OF DATE example provided for loopback which reference to:
```
{
  "local": {
    "provider": "local",
    "module": "passport-local",
    "usernameField": "username",
    "passwordField": "password",
    "authPath": "/auth/local",
    "successRedirect": "/auth/account",
    "failureRedirect": "/local",
    "failureFlash": true
  }
```
this line: "failureFlash": true, is wrong, maybe 10 years ago the flash option expected a boolean or string value but in the last loopback passport available i CAN SEE THERE IS NO SUPPORT FOR SUCH THING AS BOOLEAN OR STRING in fact it expects a function to be passed.
I'm new to node, new in loopback too, and cannot find the way to solve this, I'm going to write an article about the lack of documentation in this "amazing framework" offered as "OH MY GOD" solution because cannot believe is ranked over MEAN or any other that has much much better documentation and is possible to solve problems looking around a bit in google.
Anyways, please, can some one provide an UP TO DATE providers.json example?
This is the error i got:
```
process.nextTick(function() { throw err; });
                                  ^

TypeError: req.flash is not a function
    at allFailed (/var/www/sentineltrack/node_modules/loopback-component-passport/node_modules/passport/lib/middleware/authenticate.js:118:15)
    at attempt (/var/www/sentineltrack/node_modules/loopback-component-passport/node_modules/passport/lib/middleware/authenticate.js:167:28)
    at Strategy.strategy.fail (/var/www/sentineltrack/node_modules/loopback-component-passport/node_modules/passport/lib/middleware/authenticate.js:284:9)
    at verified (/var/www/sentineltrack/node_modules/passport-local/lib/strategy.js:82:30)
    at /var/www/sentineltrack/node_modules/loopback-component-passport/lib/passport-configurator.js:321:13
    at /var/www/sentineltrack/node_modules/loopback-datasource-juggler/lib/dao.js:1823:62
    at /var/www/sentineltrack/node_modules/loopback-datasource-juggler/lib/dao.js:1752:9
    at /var/www/sentineltrack/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:396:17
    at async.each (/var/www/sentineltrack/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:153:20)
    at _asyncMap (/var/www/sentineltrack/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:390:13)
```

**Comment by hackerunet** [comment] 2016-07-19 15:55
SOLVED: my issue was that I splitted routes in a separate file and flash usage needs to be exactly after passport init, so when I removed the flash from routes and got it into server.js again, it worked. Regarding the original problem posted by @gausie I'm getting the error messages in my final failure redirect page, so, everything seems to be working fine so far, maybe there are more available options for providers.json since the original passport library allow to programatically pass response and parameters to declared calbacks in passport configuration object. So would be really usefull if someone can post a full list of available options for providers.json just to improve the way of diagnose a problem.
regards

**Comment by loay** [comment] 2016-09-28 15:26
I this issue still persisting? Can I close this one?
Thanks

**Comment by loay** [comment] 2016-11-22 06:06
Closing issue.. if issue still persists, please leave a comment and I will re-open it. Thanks

**Closed by loay** 2016-11-22 06:06 UTC
Labels: triage, waiting

**Comment by luncht1me** [comment] 2017-02-16 02:13
@hackerunet can you post your solution in more detail please? The fact I can't get passport errors to bubble up into my loopback app is extremely frustrating. I have a validation error that I know is firing since I can console log it deep within the passport source code, but I cannot for the life of me get it up into an actual server response which I can then handle accordingly in my application.

**Comment by hackerunet** [comment] 2017-02-16 03:22
Im so sorry colin, cannot since i have abandon any effort to use
strongloop, i wasted too much time figuring out basic stuff. This simply
was messing up my productivity and i stopped using it. Best wishes there
are plenty of options out there that offers better solutions for software
development.

**Comment by smith64fx** [comment] 2017-02-16 10:57
@hackerunet 
Really sad, that you stop using it.

We just made it work to have a social login/linking for our single page application.

Did you set options.failureRedirect to true?

**Comment by luncht1me** [comment] 2017-02-16 17:20
@smith64fx we've set `failureRedirect` to a url. The url does get hit when failure happens internally to passport.

You can see my issue in more detail here: #209
